My_Calculator Milestone 5
Davidosky007/my_calculator pull request #5
Opened 2021-05-18 17:59 UTC by Davidosky007

# My_Calculator Milestone 5 
In this milestone
* App component was converted into a stateful parent component
* handleClick function was implemented in buttonPanel and button components
* total or next values were passed to the Display components to display current values
* handleClick function was passed as a clickHandler property to buttonPanel.

2021-05-18 18:42 UTC, Forison requested changes
## Status::Change required❌

# 👋  @Davidosky007 

#### You have done a good job on this one so far, You modified the app.js to class component and implemented the handleClick as required, however, there a functional flaw we have to address to get the project approved😇 .

* [ ] Let us handle the division of a number by zero well, it should return `undefined`. Currently the application throws an error when we try this computation.
* [ ] Let us address the error in the console of the browser.

#### That is it, kindly make the changes and submit a re-review🤗.

#### Happy coding😎

Addo Forison

2021-05-18 18:42 UTC, Forison commented on src/components/ButtonPanel.js
> +buttonGroups.push(['AC', '+/-', '%', '÷']);
**[Optional]**
I don't see the need of pushing into the `buttonGroups array` why not define it directly as a dimensional array, that way you don't have to perform a task of pushing.

2021-05-18 18:42 UTC, Forison commented on src/components/App.js
> +    this.handleClick = this.handleClick.bind(this);
**[Optional]**
You could use arrow function in the function definition of `handleClick` to save your self from binding it in the constructor.

2021-05-19 04:54 UTC, bellom requested changes
## Hi @Davidosky007   :clap: 

You still need to address the issue mentioned from the previous reveiwer;
In another word;
The app is broken once the user performs the following division operation by zero.
Division by zero is not handled properly yet. Let's fix this.
The reason is that when a division by zero happens, we should return an error message like `division error`

Divide a number by zero (e.g. 4 / 0)

# Status: Changes Required! ♻️ 

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-05-19 09:11 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

- [ ] OPTIONAL - The display of the calculator buttons seems quite off. Consider arranging them with a few CSS styling to make usability easier.

Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-19 09:17 UTC, merged